# Generated by Django 4.1.1 on 2022-10-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lat", models.CharField(max_length=9)),
                ("lng", models.CharField(max_length=9)),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, null=True)),
                ("last_name", models.CharField(max_length=30, null=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "Пользователь"), ("ADMIN", "Администратор")],
                        max_length=5,
                    ),
                ),
                ("age", models.IntegerField(blank=True)),
                ("location_id", models.ManyToManyField(to="users.locations")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
