# Generated by Django 4.1.1 on 2022-10-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(default="1990-01-01"),
            preserve_default=False,
        ),
    ]
