version: "3.9"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U django']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:





